GET http://localhost:8080/api/chirps

###

GET http://localhost:8080/api/chirps/0fc416dc-9134-4cfa-abe0-7b31e99a92e0

###

POST http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "I had something interesting for breakfast",
  "userId": "671da411-ccb7-41e3-b531-b1a47fa175a8"
}

###

POST http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "This is a kerfuffle opinion I need to share with the world",
  "userId": "666a1e66-e30c-4530-b64f-95e508be203f"
}

###

POST http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  "userId": "1234"
}
